# Dockerfile for Alpine

#
# Stage 1: Build application
#

FROM node:18-alpine AS build

WORKDIR /usr/src/pushti

RUN npm install -g @angular/cli@16.0.6

COPY package*.json ./
COPY . .

RUN npm install

RUN ng build --configuration=production

#
# Stage 2: Serve application via nginx
#
FROM nginx:1.27-alpine

COPY --from=build /usr/src/pushti/dist/pushti-web /usr/share/nginx/html

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80/tcp

CMD ["nginx", "-g", "daemon off;"]
